const GET_CHARACTERS = "GET_CHARACTERS";
const SET_LOADING = "SET_LOADING";
const SET_LOADING_DONE = "SET_LOADING_DONE";
const SET_PAGE = "SET_PAGE";
const SET_ERROR = "SET_ERROR";
const SET_PAGE_LOAD = "SET_PAGE_LOAD";

export { GET_CHARACTERS, SET_LOADING, SET_LOADING_DONE, SET_PAGE, SET_ERROR, SET_PAGE_LOAD };
