const GET_CHARACTERS = "GET_CHARACTERS";
const SET_LOADING = "SET_LOADING";
const SET_LOADING_DONE = "SET_LOADING_DONE";
const SET_PAGE = "SET_PAGE";

export { GET_CHARACTERS, SET_LOADING,SET_LOADING_DONE, SET_PAGE };
